export const CONTACT_DIRECTORY_COLUMN_KEYS = {
  ID: "id",
  NAME: "name",
  NO_OF_CONTACTS: "noOfContacts",
  CREATED_AT: "createdAt",
  UPDATED_AT: "updatedAt",
  ACTION: "action",
};

export const CONTACT_DIRECTORY_COLUMN_NAME = {
  ID: "id",
  NAME: "Name",
  NO_OF_CONTACTS: "No of contacts",
  CREATED_AT: "Creation at",
  UPDATED_AT: "Updated at",
  ACTION: "Action",
};

export const SORT_KEYS = [
  CONTACT_DIRECTORY_COLUMN_KEYS.ID,
  CONTACT_DIRECTORY_COLUMN_KEYS.NAME,
  CONTACT_DIRECTORY_COLUMN_KEYS.NO_OF_CONTACTS,
  CONTACT_DIRECTORY_COLUMN_KEYS.CREATED_AT,
  CONTACT_DIRECTORY_COLUMN_KEYS.UPDATED_AT,
];
