import { ROUTES_MENU } from "../../../constants";

export const TOPIC_OPTIONS = [
  ROUTES_MENU.CONTACT_MANAGEMENT,
  ROUTES_MENU.DASHBOARD,
  ROUTES_MENU.EVENT_MANAGEMENT,
  ROUTES_MENU.GIFT_MANAGEMENT,
  ROUTES_MENU.MY_PROFILE,
];
