export const INVITATION_COLUMN_KEYS = {
  ID: "id",
  NAME: "name",
  CHANNEL: "channel",
  TYPE: "type",
  CREATED_AT: "createdAt",
  UPDATED_AT: "updatedAt",
  INVITED_BY: "invitedByInfo",
  LOCATION: "location",
};

export const INVITATION_COLUMN_NAME = {
  ID: "id",
  NAME: "Name",
  CHANNEL: "Channel",
  TYPE: "Type",
  CREATED_AT: "Creation at",
  UPDATED_AT: "Updated at",
  INVITED_BY: "Invited By",
  LOCATION: "Location",
};

export const SORT_KEYS = [
  INVITATION_COLUMN_KEYS.ID,
  INVITATION_COLUMN_KEYS.NAME,
  INVITATION_COLUMN_KEYS.CHANNEL,
  INVITATION_COLUMN_KEYS.TYPE,
  INVITATION_COLUMN_KEYS.CREATED_AT,
  INVITATION_COLUMN_KEYS.UPDATED_AT,
  INVITATION_COLUMN_KEYS.INVITED_BY,
  INVITATION_COLUMN_KEYS.LOCATION,
];
