name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: [ubuntu-latest]

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Login to docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build Docker image from Docker Hub
        run: docker build -t eazyevent/eazy-event-management-ui .

      - name: Publish image to docker hub
        run: docker push eazyevent/eazy-event-management-ui:latest

  deploy:
    needs: build
    runs-on: [aws-ec2]
    steps:
      - name: Pull image from docker hub
        run: docker pull eazyevent/eazy-event-management-ui:latest
      - name: Delete old containers
        run: docker rm -f eazy-event-management-container
      - name: Run docker container
        run: docker run -d -p 3000:3000 --name eazy-event-management-container eazyevent/eazy-event-management-ui
